/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/typeThirteen.glb");
  // console.log(materials);
  materials.biru.emissive.r = 1;
  materials.biru.emissive.g = 1;
  materials.biru.emissive.b = 1;
  materials.palette.emissive.r = 0;
  materials.palette.emissive.g = 0;
  materials.palette.emissive.b = 0;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.ObjObject_1.geometry}
          material={materials.palette}
        />
        <mesh geometry={nodes.ObjObject_2.geometry} material={materials.biru} />
      </group>
    </group>
  );
}

useGLTF.preload("/typeThirteen.glb");
